### PR TITLE
Added serialization support for ImmutableMappable

### PR DESCRIPTION
**Pull request by louisdh**
Implemented correct serialization for the new (currently in beta) [ImmutableMappable protocol](https://github.com/Hearst-DD/ObjectMapper#immutablemappable-protocol-beta).

### CODE REVIEW

**Comment by tristanhimmelman** [comment]
Thanks @louisdh. Can you please add the same if case to the array mapping function as well?

**Comment by louisdh** [comment]
Ok, will do!

**Comment by louisdh** [comment]
All done

**Comment by louisdh** [comment]
@tristanhimmelman Hmm, seems like Travis isn't configured to run the unit tests?

**Comment by tristanhimmelman** [comment]
ImmutableMappable has been merged into master from another branch.

**Comment by tristanhimmelman** [comment]
Thanks again @louisdh. I made a few changes so that the MapContext is used for `ImmutableMappable` as well.

**Comment by tristanhimmelman** [comment]
@louisdh yeah thats right. I had some issue configuration Travis to run the tests. For some reason xcodebuild has trouble linking the correct version (iOS, Mac, etc) of the dependencies.

**Pull request closed without merging**
