### PR TITLE
#192 Update required version of ObjectMapper.

### PR DESCRIPTION
**Pull request by garie**

### CODE REVIEW

**Comment by tristanhimmelman** [comment]
I believe `~> 2.0` should automatically take the greatest available version up until `3.0`

**Comment by garie** [comment]
Yes but I also have ObjectMapper in my Cartfile with an =2.0, I think because of a bug in 2.1. Carthage installed and built just fine because 2.0 is valid for my Cartfile as well as yours. However, the app immediately crashed. This change would cause a Carthage error in my case that no matching versions could be found.

**Comment by tristanhimmelman** [comment]
The bug in ObjectMapper 2.1 has been resolved. You should be able to remove that dependency now.

**Comment by garie** [comment]
I know, I have, I was just trying to prevent other people from experiencing this crash.

**Comment by tristanhimmelman** [comment]
Ah i see. That should no longer happen to people however, as Cocoapods and Carthage will automatically grab ObjectMapper 2.2.2. Thanks though!

**Comment by tristanhimmelman** [comment]
On second thought, it doesn't hurt to add this extra protection 👍

**Pull request merged**
