### PR TITLE
Add functionality to automatically parse JSON to Mappable Swift classes.

### PR DESCRIPTION
**Pull request by jacoblubecki**
I wrote a little method in my own project to add this functionality and figured it'd be useful in the main project. I can reformat it and/or unstage any unwanted changes to existing project files if it's a welcome addition. Thanks for taking a look.

### CODE REVIEW

**Comment by kylebrowning** [comment]
Can you give an example of this being used?

**Comment by jacoblubecki** [comment]
```swift
Alamofire.request(.GET, "http://someurl.com/some.json").responseConvertedToMappableClass(withName: "MyObject")
```

**Comment by kylebrowning** [comment]
Doesn't seem to work when the response is an Array, but I understand why.

**Comment by jacoblubecki** [comment]
If I recall correctly, it prints out what the first array item looks like and adds a message saying that it found an array.

**Comment by kylebrowning** [comment]
I mean, consider the following. 
```
[
  {
    "title": "test",
    "body": "test\n"
  },
  {
    "title": "Hello World2",
    "body": "How are you?2\n"
  }
]
```

**Comment by kylebrowning** [comment]
Also, I tried this on a much more complex json structure.

```swift 
class test: Mappable {

		// MARK: - Properties

		var title: [AnyObject]?
		var uuid: [AnyObject]?
		var revision_log: [AnyObject]?
		var default_langcode: [AnyObject]?
		var changed: [AnyObject]?
		var revision_uid: [AnyObject]?
		var vid: [AnyObject]?
		var revision_timestamp: [AnyObject]?
		var nid: [AnyObject]?
		var path: [AnyObject]?
		var promote: [AnyObject]?
		var field_image: [AnyObject]?
		var comment: [AnyObject]?
		var uid: [AnyObject]?
		var sticky: [AnyObject]?
		var type: [AnyObject]?
		var field_tags: [AnyObject]?
		var body: [AnyObject]?
		var langcode: [AnyObject]?
		var created: [AnyObject]?
		var status: [AnyObject]?
		var revision_translation_affected: [AnyObject]?


		// MARK: - Init

		required init?(_ map: Map) { }


		// MARK: - Mappable

		func mapping(map: Map) {
			title                          <- map["title"]
			uuid                           <- map["uuid"]
			revision_log                   <- map["revision_log"]
			default_langcode               <- map["default_langcode"]
			changed                        <- map["changed"]
			revision_uid                   <- map["revision_uid"]
			vid                            <- map["vid"]
			revision_timestamp             <- map["revision_timestamp"]
			nid                            <- map["nid"]
			path                           <- map["path"]
			promote                        <- map["promote"]
			field_image                    <- map["field_image"]
			comment                        <- map["comment"]
			uid                            <- map["uid"]
			sticky                         <- map["sticky"]
			type                           <- map["type"]
			field_tags                     <- map["field_tags"]
			body                           <- map["body"]
			langcode                       <- map["langcode"]
			created                        <- map["created"]
			status                         <- map["status"]
			revision_translation_affected  <- map["revision_translation_affected"]
		}
}
```

Considering the following

```javascript
{
  "nid": [
    {
      "value": "17"
    }
  ],
  "uuid": [
    {
      "value": "f777e4cb-4f8d-47db-ac3a-1a9dbf5e6ffe"
    }
  ],
  "vid": [
    {
      "value": "17"
    }
  ],
  "langcode": [
    {
      "value": "en"
    }
  ],
  "type": [
    {
      "target_id": "article",
      "target_type": "node_type",
      "target_uuid": "0b12744b-1aeb-4450-8fc6-8376397943a6"
    }
  ],
  "title": [
    {
      "value": "test"
    }
  ],
  "uid": [
    {
      "target_id": "1",
      "target_type": "user",
      "target_uuid": "6e64b82c-7f91-4a69-8a53-672350f70758",
      "url": "/user/1"
    }
  ],
  "status": [
    {
      "value": "1"
    }
  ]
}
```

although these issues may not have to do your extensions, I think they may be reading things wrong with all the `[AnyObject]`'s

**Comment by jacoblubecki** [comment]
What is the debug output for that case? I will look into fixing it if I can, just want to know at what point its breaking.

**Comment by kylebrowning** [comment]
`"Could not convert String response to Dictionary ([String : AnyObject])"`

**Comment by jacoblubecki** [comment]
I will try to add some functionality for array cases and to print all the individual components for complex structures, but right now it will only print a single JSON structure formatted as mappable class. For now you would have to make a request for each variable, i.e:

```swift
let request = Alamofire.request(.GET, "http://someurl.com/some.json")

request.responseConvertedToMappableClass(withName: "MyObject", forKeyPath: "nid")
request.responseConvertedToMappableClass(withName: "MyObject", forKeyPath: "uuid")

// etc.
```

**Comment by jacoblubecki** [comment]
@kylebrowning Added support for those features. Let me know if you hit any new bugs.

**Comment by jacoblubecki** [comment]
@tristanhimmelman thoughts?

**Comment by tristanhimmelman** [comment]
@jacoblubecki sorry for the very slow response.

I think this addition is cool, however, I am hesitant to include it in the project as I would like to keep `AlamofireObjectMapper` as minimal as possible. This addition could potentially added a significant amount of maintenance work as ObjectMapper matures.

With that said, I still think this code is valuable. If you could set this up as an extension to AlamofireObjectMapper or even ObjectMapper, I would be happy to include a link to your project in the README.

**Comment by jacoblubecki** [comment]
That's an understandable concern. I will move the code to a standalone project and post an update here once it's setup for distribution via Cocoapods/Carthage. Thanks for taking a look!

**Pull request closed without merging**
